version: 2

models:
  # =================================================================
  # (DIMENSIONS Tests)
  # =================================================================

  # 1. (dim_date)
  - name: dim_date
    description: Standard time dimension table.
    columns:
      - name: date_key
        description: Surrogate key for date (YYYYMMDD).
        tests:
          - unique
          - not_null
      - name: date
        description: Actual calendar date.
        tests:
          - not_null

  # 2. (dim_products)
  - name: dim_products
    description: List of products sold by the company.
    columns:
      - name: product_key
        description: Surrogate key for product (PK).
        tests:
          - unique
          - not_null
      - name: is_discontinued
        description: Whether the product is discontinued (TRUE/FALSE).
        tests:
          - accepted_values:
              values: [true, false]

  # 3. (dim_customers)
  - name: dim_customers
    description: Standard customer dimension table.
    columns:
      - name: customer_key
        description: Surrogate key for customer (PK).
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Natural key for customer.
        tests:
          - not_null
          - unique 

  # 4. (dim_employees)
  - name: dim_employees
    description: Standard employee dimension table.
    columns:
      - name: employee_key
        description: Surrogate key for employee (PK).
        tests:
          - unique
          - not_null
      - name: job_title
        description: Employee job title.
        tests:
          - accepted_values:
              values: ["Sales Representative", "Vice President, Sales", "Sales Manager", "Inside Sales Coordinator"]

  # 5. (dim_shippers)
  - name: dim_shippers
    description: Shipping companies dimension.
    columns:
      - name: shipper_key
        description: Surrogate key for shipping company (PK).
        tests:
          - unique
          - not_null
      - name: shipper_company_name
        description: Shipping company name.
        tests:
          - not_null
          - unique 

  # 6. (dim_regions)
  - name: dim_regions
    description: Main geographic regions.
    columns:
      - name: region_key
        description: Surrogate key for main region (PK).
        tests:
          - unique
          - not_null
      - name: region_description
        description: Description of the region.
        tests:
          - not_null
          - unique 
          
  # 7. (dim_territories)
  - name: dim_territories
    description: Sub-geographic territories assigned to employees.
    columns:
      - name: territory_key
        description: Surrogate key for sub-region (PK).
        tests:
          - unique
          - not_null
      - name: region_key
        description: Foreign key linking to the main region.
        tests:
          - not_null
          - relationships:
              to: ref('dim_regions')
              field: region_key

  # =================================================================
  # (FACTS Tests)
  # =================================================================
  
  # 8. (fct_sales)
  - name: fct_sales
    description: Sales facts at the order line level.
    columns:
      - name: order_line_key
        description: Unique key for the order line (PK).
        tests:
          - unique
          - not_null
      
      # (Foreign Keys) 
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key
              severity: warn
      - name: product_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_key
      
  # 9. (fct_customer_interaction)
  - name: fct_customer_interaction
    description: Aggregated metrics for the customer file.
    columns:
      - name: customer_key
        description: The primary key (PK) in the fact table.
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key
      - name: total_orders_count
        description: Total number of orders.
        tests:
          - not_null
